// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Studio.Date;

#nullable disable

namespace Studio.Date.Migrations
{
    [DbContext(typeof(StudioAtendimentoContext))]
    [Migration("20260826160818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Studio.Domain.Models.AtendimentoModels", b =>
                {
                    b.Property<int>("CodigoAtendimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoAtendimento"));

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostoAtendimento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodigoAtendimento");

                    b.ToTable("Atendimento", (string)null);
                });

            modelBuilder.Entity("Studio.Domain.Models.AtendimentoProcedimentoModels", b =>
                {
                    b.Property<int>("CodigoAtendimento")
                        .HasColumnType("int");

                    b.Property<int>("CodigoProcedimento")
                        .HasColumnType("int");

                    b.Property<int>("PostoAtendimento")
                        .HasColumnType("int");

                    b.HasKey("CodigoAtendimento", "CodigoProcedimento");

                    b.ToTable("Atendimento_Procedimentos", (string)null);
                });

            modelBuilder.Entity("Studio.Domain.Models.ClienteModels", b =>
                {
                    b.Property<int>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoCliente"));

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RgCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoCliente");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Studio.Domain.Models.PagamentoPixModels", b =>
                {
                    b.Property<int>("CodPagamentoPix")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPagamentoPix"));

                    b.Property<string>("BancoPagador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoAtendimento")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaModificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomePagador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodPagamentoPix");

                    b.ToTable("Pagamentos_Pix", (string)null);
                });

            modelBuilder.Entity("Studio.Domain.Models.PagamentosCartaoModels", b =>
                {
                    b.Property<int>("CodPagamentoCartao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPagamentoCartao"));

                    b.Property<string>("BandeiraCartao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoAtendimento")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaModificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebitoCredito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCartao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCartao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroVezes")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodPagamentoCartao");

                    b.ToTable("Pagamentos_Cartao", (string)null);
                });

            modelBuilder.Entity("Studio.Domain.Models.PagamentosDinheiroModels", b =>
                {
                    b.Property<int>("CodPagamentoDinheiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPagamentoDinheiro"));

                    b.Property<string>("BancoPagador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoAtendimento")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaModificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomePagador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodPagamentoDinheiro");

                    b.ToTable("Pagamentos_Dinheiro", (string)null);
                });

            modelBuilder.Entity("Studio.Domain.Models.PostoModels", b =>
                {
                    b.Property<int>("CodigoPosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoPosto"));

                    b.Property<string>("ContaBancaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescPosto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoPosto");

                    b.ToTable("Postos", (string)null);
                });

            modelBuilder.Entity("Studio.Domain.Models.ProcedimentoModels", b =>
                {
                    b.Property<int>("CodigoProcedimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProcedimento"));

                    b.Property<string>("DescProcedimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorProcedimento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodigoProcedimento");

                    b.ToTable("Procedimentos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
